# Generated by Django 3.1.2 on 2021-05-23 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(default='', max_length=150)),
                ('message', models.TextField()),
                ('created_on', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
